CREATE DATABASE AVIONES
GO

USE AVIONES
GO

CREATE TABLE AEROPUERTOS(
Cod_IATA INT PRIMARY KEY IDENTITY(1,1),
LOCALIDAD VARCHAR(70)
)
GO

CREATE TABLE RESERVAS(
NUM_VUELO INT PRIMARY KEY IDENTITY(1,1),
FECHA VARCHAR(70),
AGENCIA INT,
PLAZAS VARCHAR(70)
)
GO

CREATE TABLE AGENCIAS(
CODIGO INT PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(70),
DIRECCION VARCHAR(70),
TELEFONO VARCHAR(70)
)
GO

CREATE TABLE AVIONES(
TIPO INT PRIMARY KEY IDENTITY(1,1),
DESCRIPCION VARCHAR(70),
LONGITUD VARCHAR(70),
ENVERGADURA VARCHAR(70),
BUTACAS VARCHAR(70),
ALCANCE VARCHAR(70)
)
GO

CREATE TABLE VUELOS(
NUM_VUELO INT PRIMARY KEY IDENTITY(1,1),
ORIGEN VARCHAR(70),
DESTINO VARCHAR(70),
HORA_SALIDA VARCHAR(70),
HORA_LLEGADA VARCHAR(70),
DURACION VARCHAR(70),
DISTANCIA VARCHAR(70),
TIPO_AVION INT
)
GO

CREATE TABLE PARTES(
NUM_PARTE INT PRIMARY KEY IDENTITY(1,1),
NUM_VUELO INT,
MAT INT,
FECHA VARCHAR(70),
HORA_SALIDA VARCHAR(70),
HORA_LLEGADA VARCHAR(70),
NIVEL_VUELO VARCHAR(70),
COMB_CONSUMIDO VARCHAR(70)
)
GO

CREATE TABLE FLOTA(
MATRICULA INT PRIMARY KEY IDENTITY(1,1),
TIPO_AVION INT,
COMPANIA INT
)
GO

CREATE TABLE COMPANIAS(
CODIGO INT PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(70)
)
GO

ALTER TABLE RESERVAS
ADD CONSTRAINT FK_RESERVAS_AGENCIA
FOREIGN KEY (AGENCIA) REFERENCES AGENCIAS(CODIGO)
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE VUELOS
ADD CONSTRAINT FK_VUELOS_AVIONES
FOREIGN KEY (TIPO_AVION) REFERENCES AVIONES(TIPO)
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE PARTES
ADD CONSTRAINT FK_PARTES_VUELOS
FOREIGN KEY (NUM_VUELO) REFERENCES VUELOS(NUM_VUELO)
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE PARTES
ADD CONSTRAINT FK_PARTES_FLOTA
FOREIGN KEY (MAT) REFERENCES FLOTA(MATRICULA)
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE FLOTA
ADD CONSTRAINT FK_FLOTA_AVIONES
FOREIGN KEY (TIPO_AVION) REFERENCES AVIONES(TIPO)
ON UPDATE NO ACTION
ON DELETE NO ACTION
GO

ALTER TABLE FLOTA
ADD CONSTRAINT FK_FLOTA_COMPANIAS
FOREIGN KEY (COMPANIA) REFERENCES COMPANIAS(CODIGO)
ON UPDATE CASCADE
ON DELETE CASCADE
GO

-----1-----
SELECT VUELOS.NUM_VUELO, DESTINO FROM VUELOS INNER JOIN PARTES ON VUELOS.NUM_VUELO = PARTES.NUM_VUELO WHERE PARTES.COMB_CONSUMIDO > (1/3) ORDER BY VUELOS.DESTINO
GO

-----2-----
SELECT DESTINO FROM VUELOS INNER JOIN AVIONES ON VUELOS.TIPO_AVION = AVIONES.TIPO WHERE AVIONES.BUTACAS > 160 AND VUELOS.HORA_SALIDA = '10:15 AM'
GO

-----3-----
SELECT TIPO, LONGITUD, ENVERGADURA FROM AVIONES INNER JOIN VUELOS ON AVIONES.TIPO = VUELOS.TIPO_AVION WHERE ENVERGADURA > (1/2) OR VUELOS.DESTINO = 'Barcelona'
GO

-----4-----
SELECT DESTINO FROM VUELOS INNER JOIN AVIONES ON AVIONES.TIPO = VUELOS.TIPO_AVION WHERE AVIONES.LONGITUD > (1/2) ORDER BY DESTINO
GO

-----5-----
SELECT NUM_PARTE FROM PARTES WHERE FECHA='11-12-13'
GO

-----6-----
SELECT ORIGEN FROM VUELOS WHERE DISTANCIA = '12KM'
GO

-----7-----
SELECT ORIGEN FROM VUELOS WHERE NUM_VUELO < 10
GO

-----8-----
SELECT ORIGEN FROM VUELOS WHERE DESTINO = 'Barcelona' AND DISTANCIA < (1/2) ORDER BY ORIGEN
GO

-----9-----
SELECT TIPO FROM AVIONES INNER JOIN VUELOS ON VUELOS.TIPO_AVION = AVIONES.TIPO WHERE VUELOS.DESTINO = 'Iberia' ORDER BY TIPO
GO

-----10-----
SELECT NUM_PARTE FROM PARTES INNER JOIN VUELOS ON VUELOS.NUM_VUELO = PARTES.NUM_VUELO WHERE VUELOS.DISTANCIA < (2/3)
GO

-----11-----
SELECT NUM_VUELO FROM VUELOS WHERE DISTANCIA = '32KM' AND ORIGEN = 'Barcelona'
GO

-----12-----
SELECT NUM_VUELO FROM VUELOS WHERE DISTANCIA > '3000KM'


-----13-----
SELECT NUM_VUELO FROM VUELOS WHERE ORIGEN = 'Bogota'

