-- Verificación de BD
IF DB_ID('TIENDA') IS NOT NULL
BEGIN
	USE MASTER
	DROP DATABASE TIENDA
END

-- CREACIÓN DE BD
CREATE DATABASE TIENDA
ON PRIMARY
(NAME = 'TIENDA.MDF',
FILENAME = 'F:\BASES DE DATOS SQL SERVER 2012\TIENDA.MDF',
SIZE = 20MB,
MAXSIZE = 40MB,
FILEGROWTH = 10%)

LOG ON
(NAME = 'TIENDA.LDF',
FILENAME = 'F:\BASES DE DATOS SQL SERVER 2012\TIENDA.LDF',
SIZE = 10MB,
MAXSIZE = 29MB,
FILEGROWTH = 10%)
GO