-- Crear base de datos
CREATE DATABASE Kinder
GO

-- Usar base de datos
USE Kinder

-- Crear tablas
CREATE TABLE ALUMNO(
ID_ALUMNO INT PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(70),
COLONIA VARCHAR(70),
FECHA VARCHAR(70)
)
GO

CREATE TABLE ESCUELA(
ID_ESCUELA INT PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(70),
DIRECCION VARCHAR(200),
ESTADO VARCHAR(70)
)
GO

CREATE TABLE MAESTRO(
ID_MAESTRO INT PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(70),
ID_ALUMNO INT,
ID_ESCUELA INT,
REGALO VARCHAR(70),
CALIFICACION INT
)

-- Crear relaciones
ALTER TABLE MAESTRO
ADD CONSTRAINT FK_MAESTRO_ALUMNOS
FOREIGN KEY (ID_ALUMNO) REFERENCES ALUMNO(ID_ALUMNO)
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE MAESTRO
ADD CONSTRAINT FK_MAESTRO_ESCUELA
FOREIGN KEY (ID_ESCUELA) REFERENCES ESCUELA(ID_ESCUELA)
ON UPDATE CASCADE
ON DELETE CASCADE
GO

-- Insertar en Alumno
INSERT INTO ALUMNO(NOMBRE, COLONIA, FECHA) VALUES('Juan','Miguel','29')
GO
INSERT INTO ALUMNO(NOMBRE, COLONIA, FECHA) VALUES('Pedro','Centro','5')
GO
INSERT INTO ALUMNO(NOMBRE, COLONIA, FECHA) VALUES('Juan','Miguel','1')
GO
INSERT INTO ALUMNO(NOMBRE, COLONIA, FECHA) VALUES('Pancho','Cayetano','29')
GO
INSERT INTO ALUMNO(NOMBRE, COLONIA, FECHA) VALUES('Poncho','Cayetano','10')
GO

-- Insertar en Escuela
INSERT INTO ESCUELA(NOMBRE, DIRECCION, ESTADO) VALUES('ITESI','ALDAMA','SALAMANCA'),
('CBTIS','FOVISTE','IRAPUATO'),
('ITESI','ALDAMA','IRAPUATO'),
('CBTIS','FOVISTE','ABASOLO'),
('ITESA','VILLAS','SALAMANCA')
GO

-- Insertar en Maestro
INSERT INTO MAESTRO(NOMBRE, ID_ALUMNO, ID_ESCUELA, REGALO, CALIFICACION) VALUES('GIO', 1, 2, 'RINES', 100),
('JUAN', 4, 5, 'RP', 30),
('YO', 3, 2,'COCHE', 100),
('JUAN', 1, 1, 'RP', 80),
('VIOLE', 5, 3, 'FON', 70),
('GIO', 2, 3, 'COCHE', 70),
('VIOLE', 3, 5, 'RINES', 30)
GO


-- Consultas
-------------------------------------------------------------------
SELECT NOMBRE FROM ALUMNO WHERE NOMBRE LIKE 'J%'
GO

SELECT NOMBRE, FECHA FROM ALUMNO WHERE COLONIA = 'Cayetano'
GO

SELECT NOMBRE FROM ESCUELA WHERE DIRECCION = 'ALDAMA'
GO

SELECT ID_ESCUELA, DIRECCION FROM ESCUELA WHERE NOMBRE = 'CBTIS'
GO

SELECT * FROM MAESTRO
GO

SELECT MAESTRO.REGALO, ALUMNO.NOMBRE, MAESTRO.NOMBRE FROM MAESTRO INNER JOIN ALUMNO ON MAESTRO.ID_ALUMNO = ALUMNO.ID_ALUMNO WHERE MAESTRO.CALIFICACION = 100
GO

SELECT ALUMNO.NOMBRE, ALUMNO.COLONIA, ESCUELA.DIRECCION, MAESTRO.NOMBRE FROM MAESTRO INNER JOIN ALUMNO ON MAESTRO.ID_ALUMNO = ALUMNO.ID_ALUMNO INNER JOIN ESCUELA ON MAESTRO.ID_ESCUELA = ESCUELA.ID_ESCUELA WHERE MAESTRO.CALIFICACION = 70 AND MAESTRO.REGALO = 'FON'
GO